### PR TITLE
Add warmup when loading models

### PR DESCRIPTION
**Pull request by Zhangky11**
## Description
Add warmup steps in ` modules/ui_model_menu.py `.
Performance in https://github.com/analytics-zoo/nano/issues/1046

### CODE REVIEW

**Review by sgwhat — COMMENTED** [review]
Is this about directly inputting a "hello" to chat for a warm-up?

**Comment by Zhangky11** [comment]
> Is this about directly inputting a "hello" to chat for a warm-up?

That's right. And the "hello" input and its reply won't be recorded in history chat. It won't influence future chat.

**Comment by sgwhat** [comment]
> > Is this about directly inputting a "hello" to chat for a warm-up?
> 
> That's right. And the "hello" input and its reply won't be recorded in history chat. It won't influence future chat.

Nice!

**Review by sgwhat — APPROVED** [review]
LGTM

**Pull request merged**
